### ISSUE TITLE
Anthropic IncompleteOutputException is not triggered

### ISSUE THREAD

**Issue by palako** [Sagittal-ai/instructor#1]
Within `function_calls.py`, the `parse_anthropic_json` method tries to convert to `model_validate_json` without first checking if the response is complete, which raises a `ValueError` exception due to the malformed JSON.

Before trying to `model_validate_json`, the code should check `completion.stop_reason` and raise an `IncompleteOutputException` if the value is `'max_tokens'`

**Comment by neo-sagittal** [comment]
I'm on it!

**Comment by neo-sagittal** [comment]
I'm on it!

**Comment by neo-sagittal** [comment]
I'm on it!
